create table TB_TRANSACAO (
    id bigint generated by default as identity,
    aluno_id bigint,
    produto varchar(100),
    beneficiario varchar(200),
    data_criacao timestamp not null,
    valor decimal(19, 2),
    primary key (id),
    foreign key (aluno_id) REFERENCES TB_ALUNO(id)
)