spring:
  datasource:
    url: jdbc:h2:~\fiapcreditcarddatabase;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  batch:
    initialize-schema: ALWAYS

fileAlunos:
  path:  /Users/temp/lista_alunos.txt
  chunk: lista_alunos.txt

fileTransacoes:
  path:  /Users/temp/lista_transacoes.txt
  chunk: lista_transacoes.txt


